version: "3.9"

services:
  postgres:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: link_cut
    ports:
      - "5431:5432"
